// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitTests_ExpenseAPI;

#nullable disable

namespace UnitTests_ExpenseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319204236_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("UnitTests_ExpenseAPI.Expense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateOnly(9999, 12, 31),
                            Value = 10.0m
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateOnly(9999, 12, 31),
                            Description = "Hamburguer",
                            Value = 25.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
