// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitTests_ExpenseAPI;

#nullable disable

namespace UnitTests_ExpenseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322224021_CreateCategoryModel")]
    partial class CreateCategoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("UnitTests_ExpenseAPI.Expense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryId = 1,
                            Date = new DateOnly(9999, 12, 31),
                            Value = 10.0m
                        },
                        new
                        {
                            ID = 2,
                            CategoryId = 2,
                            Date = new DateOnly(9999, 12, 31),
                            Value = 25.0m
                        });
                });

            modelBuilder.Entity("UnitTests_ExpenseAPI.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HexadecimalColor")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Ifood",
                            HexadecimalColor = "#FF0000"
                        },
                        new
                        {
                            ID = 2,
                            Description = "AppleStore",
                            HexadecimalColor = "#eb4034"
                        });
                });

            modelBuilder.Entity("UnitTests_ExpenseAPI.Expense", b =>
                {
                    b.HasOne("UnitTests_ExpenseAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
