###
POST http://localhost:5239/api/category
Content-Type: application/json

{
  "Description":"Uber",
  "HexadecimalColor": "#8c97ab"
}

###
GET http://localhost:5239/api/category



###
POST http://localhost:5239/api/category/delete/5
