###
POST http://localhost:5239/api/category
Content-Type: application/json

{
  "Description":"Drogas",
  "HexadecimalColor": "#67eb8a"
}

###
GET http://localhost:5239/api/category



###
POST http://localhost:5239/api/category/delete/5
